default_install_hook_types:
  - pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: check-symlinks
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude: ".(md|rst)$"
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: pretty-format-json
        args:
          - --autofix
  # YAML
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: ["-d relaxed"]
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        language: system
  # EditorConfig
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.6.0
    hooks:
      - id: editorconfig-checker
  # Spelling
  - repo: https://github.com/crate-ci/typos
    rev: v1.42.0
    hooks:
      - id: typos
  # Png
  - repo: https://github.com/oxipng/oxipng
    rev: v10.0.0
    hooks:
      - id: oxipng
        args: ["-o", "4", "--strip", "safe", "--alpha"]
  # Github action
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint-system
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.20.0
    hooks:
      - id: zizmor
  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  # Markdown
  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: v0.0.216
    hooks:
      - id: rumdl-fmt
        args:
          - --disable
          - MD013
