default_install_hook_types:
  - pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: check-symlinks
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude: ".(md|rst)$"
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: pretty-format-json
        args:
          - --autofix
  # YAML
  - repo: https://github.com/adrienverge/yamllint.git
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530 # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: ["-d relaxed"]
  - repo: https://github.com/google/yamlfmt
    rev: 21ca5323a9c87ee37a434e0ca908efc0a89daa07 # frozen: v0.21.0
    hooks:
      - id: yamlfmt
        language: system
  # EditorConfig
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: e8b4e28241a9ae8296ba6e4a491b5da4eda73283 # frozen: 3.11.1
    hooks:
      - id: editorconfig-checker
  # Spelling
  - repo: https://github.com/crate-ci/typos
    rev: 8a48f81b6c64dcfea44b3633223084c4be58ac5f # frozen: v1.49.0
    hooks:
      - id: typos
  # Png
  - repo: https://github.com/oxipng/oxipng
    rev: 340cd9878d8d8289f09fa101b48a8f5f0b7783f4 # frozen: v10.2.0
    hooks:
      - id: oxipng
        args: ["-o", "4", "--strip", "safe", "--alpha"]
  # Github action
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # frozen: v1.7.12
    hooks:
      - id: actionlint-system
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa # frozen: v1.29.0
    hooks:
      - id: zizmor
  # Security
  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e # frozen: v8.30.1
    hooks:
      - id: gitleaks
  # Markdown
  - repo: https://github.com/rvben/rumdl-pre-commit
    rev: 086d06076d51d170b35c3aedfb54368f933b2fb1 # frozen: v0.2.54
    hooks:
      - id: rumdl-fmt
        args:
          - --disable
          - MD013
